name: Update WSPR Table

on:
  schedule:
    - cron: '*/30 * * * *'  # elke 30 minuten
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install requests
      run: pip install requests
    - name: Generate HTML
      run: python wspr_fetch.py
    - name: Commit HTML
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add index.html
        git commit -m "Update WSPR HTML" || echo "No changes to commit"
        git push
